# Generated by Django 5.1.3 on 2024-12-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_talento_humano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelacademico',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nivelacademico',
            name='vigencia',
            field=models.PositiveIntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarifa',
            name='vigencia',
            field=models.PositiveIntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='nivelacademico',
            unique_together={('nombre', 'vigencia')},
        ),
        migrations.AlterUniqueTogether(
            name='tarifa',
            unique_together={('nivel_academico', 'anios_experiencia_min', 'anios_experiencia_max', 'vigencia')},
        ),
    ]
