# Generated by Django 5.1.3 on 2024-12-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_talento_humano', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='estado',
            new_name='estado_revision',
        ),
    ]
