# Generated by Django 5.1.3 on 2025-05-28 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDirectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(help_text='Diccionario con claves de pregunta_id y valores con respuesta')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evaluación Estudiante',
                'verbose_name_plural': 'Evaluaciones Estudiantes',
                'db_table': 'evaluacion_estudiante',
            },
        ),
        migrations.CreateModel(
            name='PreguntaDirectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionDirectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(help_text='Diccionario con claves de pregunta_id y valores con respuesta')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('docente_evaluado', models.ForeignKey(limit_choices_to={'fk_rol__rol': 'D'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_directivos', to='home.empleado')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_directivo', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_directivos', to='home.periodo')),
            ],
            options={
                'verbose_name': 'Evaluación Directivo',
                'verbose_name_plural': 'Evaluaciones Directivos',
                'db_table': 'evaluacion_directivo',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(help_text='Diccionario con claves de pregunta_id y valores con respuesta')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_docente', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_docentes', to='home.periodo')),
            ],
            options={
                'verbose_name': 'Evaluación Docente',
                'verbose_name_plural': 'Evaluaciones Docentes',
                'db_table': 'evaluacion_docente',
            },
        ),
    ]
