# Generated by Django 5.1.3 on 2025-05-28 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Evaluacion', '0001_initial'),
        ('admisiones', '0001_initial'),
        ('home', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='admisiones.estudiantes'),
        ),
        migrations.AddField(
            model_name='evaluacionestudiante',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='home.materia'),
        ),
        migrations.AddField(
            model_name='evaluacionestudiante',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_estudiantes', to='home.periodo'),
        ),
        migrations.AddField(
            model_name='preguntadirectivo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='Evaluacion.categoriadirectivo'),
        ),
        migrations.AddField(
            model_name='preguntadocente',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='Evaluacion.categoriadocente'),
        ),
        migrations.AddField(
            model_name='preguntaestudiante',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='Evaluacion.categoriaestudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluaciondirectivo',
            unique_together={('evaluador', 'docente_evaluado', 'periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluaciondocente',
            unique_together={('docente', 'periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluacionestudiante',
            unique_together={('estudiante', 'materia', 'periodo')},
        ),
    ]
