# Generated by Django 5.1.3 on 2025-05-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0002_evaluaciondirectivo_evaluaciondocente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriadirectivo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='categoriadocente',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='categoriaestudiante',
            name='descripcion',
        ),
    ]
