# Generated by Django 5.1.3 on 2025-05-28 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0002_initial'),
        ('home', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionestudiante',
            name='docente_evaluado',
            field=models.ForeignKey(default=1, limit_choices_to={'fk_rol__rol': 'D'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_estudiantes_docentes', to='home.empleado'),
            preserve_default=False,
        ),
    ]
