# Generated by Django 5.1.3 on 2025-05-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0003_remove_categoriadirectivo_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluaciondocente',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='evaluaciondocente',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='evaluacionestudiante',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='evaluacionestudiante',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='evaluacionestudiante',
            name='pregunta',
        ),
        migrations.DeleteModel(
            name='EvaluacionDirectivo',
        ),
        migrations.DeleteModel(
            name='EvaluacionDocente',
        ),
        migrations.DeleteModel(
            name='EvaluacionEstudiante',
        ),
    ]
