# Generated by Django 5.1.3 on 2025-06-05 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0003_evaluacionestudiante_docente_evaluado'),
        ('home', '0085_alter_cargaacademica_fecha_aprobacion_contabilidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocentePostgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_docente', to='home.empleado'),
        ),
        migrations.CreateModel(
            name='PreguntaDocentePostgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='Evaluacion.categoriadocentepostgrado')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionDocentePostgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(help_text='Diccionario con claves de pregunta_id y valores con respuesta')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_docente_postgrado', to='home.empleado')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_docentes_postgrado', to='home.periodo')),
            ],
            options={
                'verbose_name': 'Evaluación Docente Postgrado',
                'verbose_name_plural': 'Evaluaciones Docentes De Postgrado',
                'db_table': 'evaluacion_docente_postgrado',
                'unique_together': {('docente', 'periodo')},
            },
        ),
    ]
