# Generated by Django 5.1.3 on 2025-06-03 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0003_evaluacionestudiante_docente_evaluado'),
        ('home', '0085_alter_cargaacademica_fecha_aprobacion_contabilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'fk_rol__rol': 'D'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_docente', to='home.empleado'),
        ),
    ]
