# Generated by Django 5.1.3 on 2025-06-03 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0004_alter_evaluaciondocente_docente'),
        ('home', '0085_alter_cargaacademica_fecha_aprobacion_contabilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_docente', to='home.empleado'),
        ),
    ]
