# Generated by Django 5.1.3 on 2025-05-20 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0004_remove_evaluaciondocente_docente_and_more'),
        ('admisiones', '0008_remove_materiaaprobada_fecha_finalizacion_and_more'),
        ('home', '0062_alter_materiaaprobada_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionDirectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.PositiveSmallIntegerField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('directivo', models.ForeignKey(limit_choices_to={'fk_rol__rol': 'DR'}, on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
                ('docente_evaluado', models.ForeignKey(limit_choices_to={'fk_rol__rol': 'D'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_directivos', to='home.usuario')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.preguntadirectivo')),
            ],
            options={
                'verbose_name': 'Evaluación Directivo',
                'verbose_name_plural': 'Evaluaciones Directivos',
                'db_table': 'evaluacion_directivo',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.PositiveSmallIntegerField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(limit_choices_to={'fk_rol__rol': 'D'}, on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.preguntadocente')),
            ],
            options={
                'verbose_name': 'Evaluación Docente',
                'verbose_name_plural': 'Evaluaciones Docentes',
                'db_table': 'evaluacion_docente',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.PositiveSmallIntegerField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admisiones.estudiantes')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.materia')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evaluacion.preguntaestudiante')),
            ],
            options={
                'verbose_name': 'Evaluación Estudiante',
                'verbose_name_plural': 'Evaluaciones Estudiantes',
                'db_table': 'evaluacion_estudiante',
            },
        ),
    ]
