# Generated by Django 5.1.3 on 2025-06-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0004_categoriadocentepostgrado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriadirectivo',
            options={'verbose_name': 'Categoria Directivos', 'verbose_name_plural': 'Categorias Directivos'},
        ),
        migrations.AlterModelOptions(
            name='categoriadocente',
            options={'verbose_name': 'Categoria Docentes', 'verbose_name_plural': 'Categorias Docentes'},
        ),
        migrations.AlterModelOptions(
            name='categoriadocentepostgrado',
            options={'verbose_name': 'Categoria Docente Postgrado', 'verbose_name_plural': 'Categorias Docentes Postgrado'},
        ),
        migrations.AlterModelOptions(
            name='categoriaestudiante',
            options={'verbose_name': 'Categoria Estudiantes', 'verbose_name_plural': 'Categorias Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='preguntadirectivo',
            options={'verbose_name': 'Pregunta Directivos', 'verbose_name_plural': 'Preguntas Directivos'},
        ),
        migrations.AlterModelOptions(
            name='preguntadocente',
            options={'verbose_name': 'Pregunta Docentes', 'verbose_name_plural': 'Preguntas Docentes'},
        ),
        migrations.AlterModelOptions(
            name='preguntadocentepostgrado',
            options={'verbose_name': 'Pregunta Docente Postgrado', 'verbose_name_plural': 'Preguntas Docentes Postgrado'},
        ),
        migrations.AlterModelOptions(
            name='preguntaestudiante',
            options={'verbose_name': 'Pregunta Estudiantes', 'verbose_name_plural': 'Preguntas Estudiantes'},
        ),
        migrations.AlterModelTable(
            name='categoriadirectivo',
            table='categorias_directivos',
        ),
        migrations.AlterModelTable(
            name='categoriadocente',
            table='categorias_docentes',
        ),
        migrations.AlterModelTable(
            name='categoriadocentepostgrado',
            table='categorias_docentes_postgrado',
        ),
        migrations.AlterModelTable(
            name='categoriaestudiante',
            table='categorias_estudiantes',
        ),
        migrations.AlterModelTable(
            name='preguntadirectivo',
            table='preguntas_directivos',
        ),
        migrations.AlterModelTable(
            name='preguntadocente',
            table='preguntas_docentes',
        ),
        migrations.AlterModelTable(
            name='preguntadocentepostgrado',
            table='preguntas_docentes_postgrado',
        ),
        migrations.AlterModelTable(
            name='preguntaestudiante',
            table='preguntas_estudiantes',
        ),
    ]
