# Generated by Django 5.1.3 on 2025-05-20 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0005_evaluaciondirectivo_evaluaciondocente_and_more'),
        ('home', '0062_alter_materiaaprobada_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciondirectivo',
            name='directivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario'),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario'),
        ),
    ]
