# Generated by Django 5.1.3 on 2025-05-20 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0006_alter_evaluaciondirectivo_directivo_and_more'),
        ('home', '0062_alter_materiaaprobada_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciondirectivo',
            name='directivo',
            field=models.ForeignKey(limit_choices_to={'fk_rol__rol': 'DR'}, on_delete=django.db.models.deletion.CASCADE, to='home.usuario'),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'fk_rol__rol': 'D'}, on_delete=django.db.models.deletion.CASCADE, to='home.usuario'),
        ),
    ]
