# Generated by Django 5.1.3 on 2025-05-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0008_remove_evaluaciondirectivo_directivo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluaciondirectivo',
            old_name='docente',
            new_name='evaluador',
        ),
    ]
