# Generated by Django 5.1.3 on 2025-05-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0009_rename_docente_evaluaciondirectivo_evaluador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacionestudiante',
            options={},
        ),
        migrations.RemoveField(
            model_name='evaluacionestudiante',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='evaluacionestudiante',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='evaluacionestudiante',
            name='respuestas',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='evaluacionestudiante',
            table=None,
        ),
    ]
