# Generated by Django 5.1.3 on 2025-05-23 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0010_alter_evaluacionestudiante_options_and_more'),
        ('admisiones', '0009_remove_estudiantes_correo_personal_and_more'),
        ('home', '0062_alter_materiaaprobada_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacionestudiante',
            options={'verbose_name': 'Evaluación Estudiante', 'verbose_name_plural': 'Evaluaciones Estudiantes'},
        ),
        migrations.AlterField(
            model_name='evaluacionestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='admisiones.estudiantes'),
        ),
        migrations.AlterField(
            model_name='evaluacionestudiante',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='home.materia'),
        ),
        migrations.AlterField(
            model_name='evaluacionestudiante',
            name='respuestas',
            field=models.JSONField(help_text='Diccionario con claves de pregunta_id y valores con respuesta'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluacionestudiante',
            unique_together={('estudiante', 'materia')},
        ),
        migrations.AlterModelTable(
            name='evaluacionestudiante',
            table='evaluacion_estudiante',
        ),
    ]
