# Generated by Django 5.1.3 on 2025-05-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0012_remove_evaluaciondocente_pregunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluaciondirectivo',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='evaluaciondirectivo',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='evaluaciondirectivo',
            name='respuestas',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
