# Generated by Django 5.1.3 on 2025-05-23 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0014_evaluaciondocente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluaciondocente',
            name='usuario',
        ),
    ]
