# Generated by Django 5.1.3 on 2025-05-26 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion', '0015_remove_evaluaciondocente_usuario'),
        ('admisiones', '0009_remove_estudiantes_correo_personal_and_more'),
        ('home', '0062_alter_materiaaprobada_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluacionestudiante',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='evaluaciondirectivo',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_directivos', to='home.periodo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluaciondocente',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_docentes', to='home.periodo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionestudiante',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_estudiantes', to='home.periodo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluaciondirectivo',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_directivo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluaciondirectivo',
            name='respuestas',
            field=models.JSONField(help_text='Diccionario con claves de pregunta_id y valores con respuesta'),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluaciondocente',
            name='respuestas',
            field=models.JSONField(help_text='Diccionario con claves de pregunta_id y valores con respuesta'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluaciondirectivo',
            unique_together={('evaluador', 'docente_evaluado', 'periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluaciondocente',
            unique_together={('docente', 'periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluacionestudiante',
            unique_together={('estudiante', 'materia', 'periodo')},
        ),
    ]
