# Generated by Django 5.1.3 on 2025-05-28 13:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.BigIntegerField(default=0, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fk_tipo_documento', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.tipodocumento')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.programa')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.semestre')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='MateriaAprobada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aprobacion', models.DateField(default=django.utils.timezone.now)),
                ('estado_aprobacion', models.CharField(choices=[('aprobada', 'Aprobada'), ('reprobada', 'Reprobada')], max_length=10)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admisiones.estudiantes')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.materia')),
            ],
            options={
                'verbose_name': 'Materia Cursada',
                'verbose_name_plural': 'Materias Cursadas',
                'db_table': 'materia_cursada',
                'unique_together': {('estudiante', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admisiones.estudiantes')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.periodo')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'Matricula',
                'unique_together': {('estudiante', 'materia', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='Prerrequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_principal', to='home.materia')),
                ('prerequisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_requerida', to='home.materia')),
            ],
            options={
                'verbose_name': 'Prerrequisito',
                'verbose_name_plural': 'Prerrequisitos',
                'db_table': 'Prerrequisito',
                'unique_together': {('materia', 'prerequisito')},
            },
        ),
    ]
