# Generated by Django 5.1.3 on 2025-05-19 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='codigo_docente',
        ),
    ]
