# Generated by Django 5.1.3 on 2025-06-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estudiantes',
            table='estudiantes',
        ),
        migrations.AlterModelTable(
            name='matricula',
            table='matriculas',
        ),
        migrations.AlterModelTable(
            name='prerrequisito',
            table='prerrequisitos',
        ),
    ]
