# Generated by Django 5.1.3 on 2025-05-20 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0002_remove_estudiantes_codigo_docente'),
        ('home', '0061_remove_pensum_fecha_apertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='fk_tipo_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tipodocumento'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='numero_documento',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
