# Generated by Django 5.1.3 on 2025-05-20 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0003_estudiantes_fecha_nacimiento_and_more'),
        ('home', '0061_remove_pensum_fecha_apertura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='codigo_estudiante',
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='fk_tipo_documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.tipodocumento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='numero_documento',
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
