# Generated by Django 5.1.3 on 2025-05-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0005_alter_estudiantes_fk_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='correo_personal',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
