# Generated by Django 5.1.3 on 2025-05-20 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0006_estudiantes_correo_personal_and_more'),
        ('home', '0062_alter_materiaaprobada_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaAprobada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('estado_aprobacion', models.CharField(choices=[('aprobada', 'Aprobada'), ('reprobada', 'Reprobada')], max_length=10)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admisiones.estudiantes')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.materia')),
            ],
            options={
                'verbose_name': 'Materia Cursada',
                'verbose_name_plural': 'Materias Cursadas',
                'db_table': 'materia_cursada',
                'unique_together': {('estudiante', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admisiones.estudiantes')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.materia')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'Matricula',
                'unique_together': {('estudiante', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='Prerrequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_principal', to='home.materia')),
                ('prerequisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_requerida', to='home.materia')),
            ],
            options={
                'verbose_name': 'Prerrequisito',
                'verbose_name_plural': 'Prerrequisitos',
                'db_table': 'Prerrequisito',
                'unique_together': {('materia', 'prerequisito')},
            },
        ),
    ]
