# Generated by Django 5.1.3 on 2025-05-20 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0007_materiaaprobada_matricula_prerrequisito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaaprobada',
            name='fecha_finalizacion',
        ),
        migrations.RemoveField(
            model_name='materiaaprobada',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='materiaaprobada',
            name='fecha_aprobacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
