# Generated by Django 5.1.3 on 2025-05-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0008_remove_materiaaprobada_fecha_finalizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='correo_personal',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='nombre_completo',
        ),
    ]
