# Generated by Django 5.1.3 on 2025-05-26 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0009_remove_estudiantes_correo_personal_and_more'),
        ('home', '0062_alter_materiaaprobada_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matricula',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.periodo'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('estudiante', 'materia', 'periodo')},
        ),
    ]
