# Generated by Django 5.1.3 on 2024-12-09 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'db_table': 'tipo_documentos',
            },
        ),
        migrations.CreateModel(
            name='NivelAcademico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tarifa_base_por_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigencia', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Nivel Académico',
                'verbose_name_plural': 'Niveles Académicos',
                'db_table': 'niveles_academicos',
                'unique_together': {('nombre', 'vigencia')},
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=255)),
                ('primer_nombre', models.CharField(max_length=255)),
                ('segundo_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('primer_apellido', models.CharField(max_length=255)),
                ('segundo_apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_documento', models.BigIntegerField(unique=True)),
                ('fecha_expedicion_documento', models.DateField(blank=True, null=True)),
                ('lugar_expedicion_documento', models.CharField(blank=True, max_length=255, null=True)),
                ('sexo', models.CharField(max_length=50)),
                ('telefono_fijo', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(max_length=15)),
                ('correo_personal', models.EmailField(max_length=254)),
                ('estado_civil', models.CharField(blank=True, max_length=255, null=True)),
                ('ultimo_nivel_estudio', models.CharField(blank=True, max_length=255, null=True)),
                ('eps', models.CharField(max_length=255)),
                ('arl', models.CharField(max_length=255)),
                ('afp', models.CharField(max_length=255)),
                ('caja_compensacion', models.CharField(max_length=255)),
                ('direccion_residencia', models.CharField(max_length=255)),
                ('departamento_residencia', models.CharField(max_length=255)),
                ('ciudad_residencia', models.CharField(max_length=255)),
                ('barrio_residencia', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_revision', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_app', to=settings.AUTH_USER_MODEL)),
                ('fk_creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL)),
                ('fk_modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_modificados', to=settings.AUTH_USER_MODEL)),
                ('fk_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rol')),
                ('fk_tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipodocumento')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='DetalleExperienciaLaboral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('anios_experiencia', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_experiencia_laboral', to='home.usuario')),
            ],
            options={
                'verbose_name': 'Detalle Experiencia Laboral',
                'verbose_name_plural': 'Detalles Experiencia Laboral',
                'db_table': 'detalles_exp_laboral',
            },
        ),
        migrations.CreateModel(
            name='DetalleAcademico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(max_length=255)),
                ('titulo_obtenido', models.CharField(max_length=255)),
                ('fecha_graduacion', models.DateField(blank=True, null=True)),
                ('nivel_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.nivelacademico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_academicos', to='home.usuario')),
            ],
            options={
                'verbose_name': 'Detalle Académico',
                'verbose_name_plural': 'Detalles Académicos',
                'db_table': 'detalles_academicos',
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anios_experiencia_min', models.PositiveIntegerField()),
                ('anios_experiencia_max', models.PositiveIntegerField()),
                ('tarifa_por_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigencia', models.PositiveIntegerField()),
                ('nivel_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='home.nivelacademico')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'db_table': 'tarifas',
                'unique_together': {('nivel_academico', 'anios_experiencia_min', 'anios_experiencia_max', 'vigencia')},
            },
        ),
    ]
