# Generated by Django 5.1.3 on 2024-12-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='url_hoja_de_vida',
            field=models.URLField(blank=True, null=True),
        ),
    ]
