# Generated by Django 5.1.3 on 2024-12-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usuario_url_hoja_de_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultimo_grado_academico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
