# Generated by Django 5.1.3 on 2024-12-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_usuario_ultimo_grado_academico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleexperiencialaboral',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='detalleexperiencialaboral',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
