# Generated by Django 5.1.3 on 2024-12-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_detalleexperiencialaboral_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleexperiencialaboral',
            name='anios_experiencia',
        ),
    ]
