# Generated by Django 5.1.3 on 2024-12-13 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_afp_arl_cajas_compensacion_departamentos_eps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cajas_compensacion',
            new_name='CajaCompensacion',
        ),
        migrations.RenameModel(
            old_name='departamentos',
            new_name='Departamento',
        ),
        migrations.AlterModelOptions(
            name='cajacompensacion',
            options={'verbose_name': 'Caja de compensación', 'verbose_name_plural': 'Cajas de compensación'},
        ),
    ]
