# Generated by Django 5.1.3 on 2024-12-15 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_cajas_compensacion_cajacompensacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ultimo_grado_academico',
        ),
    ]
