# Generated by Django 5.1.3 on 2024-12-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_usuario_activo_alter_usuario_afp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_institucion', models.CharField(blank=True, max_length=255, null=True)),
                ('principal_seccional', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento_ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio_ubicacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'db_table': 'instituciones',
            },
        ),
    ]
