# Generated by Django 5.1.3 on 2024-12-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_eps_codigo_eps'),
    ]

    operations = [
        migrations.AddField(
            model_name='eps',
            name='regimen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
