# Generated by Django 5.1.3 on 2024-12-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_eps_regimen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eps',
            name='regimen',
        ),
    ]
