# Generated by Django 5.1.3 on 2024-12-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_eps_regimen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eps',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
