# Generated by Django 5.1.3 on 2025-01-22 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_usuario_eps_usuario_fk_eps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=255, unique=True)),
                ('materia', models.CharField(blank=True, max_length=255, null=True)),
                ('credito', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'materias',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=255, unique=True)),
                ('fecha_apertura', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'db_table': 'periodos',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=255, unique=True)),
                ('programa', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'db_table': 'programas',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'db_table': 'semestres',
            },
        ),
        migrations.CreateModel(
            name='CargaAcademica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horas_asignadas', models.CharField(blank=True, max_length=255, null=True)),
                ('materia_compartida', models.BooleanField(default=False)),
                ('fk_docente_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
                ('fk_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.materia')),
                ('fk_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.periodo')),
                ('fk_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.programa')),
                ('fk_semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.semestre')),
            ],
            options={
                'verbose_name': 'Carga Acádemica',
                'verbose_name_plural': 'Cargas Acádemicas',
                'db_table': 'cargas_academicas',
            },
        ),
    ]
