# Generated by Django 5.1.3 on 2025-01-24 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_materia_periodo_programa_semestre_cargaacademica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programa',
            old_name='codigo',
            new_name='codigo_snies',
        ),
        migrations.AddField(
            model_name='programa',
            name='nivel_formacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.nivelacademico'),
        ),
        migrations.AddField(
            model_name='programa',
            name='sede',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
