# Generated by Django 5.1.3 on 2025-01-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_codigo_programa_codigo_snies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='sede_donde_labora',
            new_name='fk_sede_donde_labora',
        ),
        migrations.AlterField(
            model_name='programa',
            name='nivel_formacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
