# Generated by Django 5.1.3 on 2025-01-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_sede_donde_labora_usuario_fk_sede_donde_labora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fk_sede_donde_labora',
            new_name='fk_sedes',
        ),
    ]
