# Generated by Django 5.1.3 on 2025-01-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_fk_sede_donde_labora_usuario_fk_sedes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fk_sedes',
        ),
    ]
