# Generated by Django 5.1.3 on 2025-01-27 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_usuario_fk_sedes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fk_sedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sedes'),
        ),
    ]
