# Generated by Django 5.1.3 on 2025-01-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_usuario_fk_sedes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sedes',
            new_name='Sede',
        ),
    ]
