# Generated by Django 5.1.3 on 2025-01-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_sedes_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fk_sedes',
        ),
        migrations.AddField(
            model_name='usuario',
            name='sede_donde_labora',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
