# Generated by Django 5.1.3 on 2025-01-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_usuario_fk_sedes_usuario_sede_donde_labora'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaacademica',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
