# Generated by Django 5.1.3 on 2025-01-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_cargaacademica_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='año',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='programa',
            name='numero_semestres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fecha_apertura',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Apertura'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='periodo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Periodo'),
        ),
    ]
