# Generated by Django 5.1.3 on 2025-01-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_periodo_año_programa_numero_semestres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='año',
            field=models.CharField(max_length=255, unique=True, verbose_name='Año'),
        ),
    ]
