# Generated by Django 5.1.3 on 2025-01-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_periodo_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='metodologia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='semestre',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='codigo_snies',
            field=models.CharField(max_length=255, unique=True, verbose_name='Código SNIES'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='nivel_formacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nivel de Formación'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='numero_semestres',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de Semestres'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='programa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Programa'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='sede',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='semestre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Semestre'),
        ),
    ]
