# Generated by Django 5.1.3 on 2025-01-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_materia_metodologia_semestre_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='credito',
        ),
        migrations.AddField(
            model_name='materia',
            name='creditos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de Créditos'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='codigo',
            field=models.CharField(max_length=255, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='materia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='metodologia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Metodología'),
        ),
    ]
