# Generated by Django 5.1.3 on 2025-01-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_materia_credito_materia_creditos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaacademica',
            name='valor_a_pagar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor a Pagar'),
        ),
    ]
