# Generated by Django 5.1.3 on 2025-01-29 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_cargaacademica_valor_a_pagar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargaacademica',
            name='horas_asignadas',
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='horas_semanales',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Horas Semanales'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='fk_docente_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario', verbose_name='Docente Asignado'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='fk_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.materia', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='fk_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.periodo', verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='fk_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.programa', verbose_name='Programa'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='fk_semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.semestre', verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='materia_compartida',
            field=models.BooleanField(default=False, verbose_name='Materia Compartida'),
        ),
    ]
