# Generated by Django 5.1.3 on 2025-01-30 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_usuario_auth_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='año',
            new_name='year',
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio Contrato')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin Contrato')),
                ('tipo_contrato', models.CharField(max_length=255, verbose_name='Tipo Contrato')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='home.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
