# Generated by Django 5.1.3 on 2025-01-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_rename_año_periodo_year_contrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AddField(
            model_name='contrato',
            name='dias_contrato',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Dias'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo Contrato'),
        ),
        migrations.AlterModelTable(
            name='contrato',
            table='contrato',
        ),
    ]
