# Generated by Django 5.1.3 on 2025-01-31 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_contrato_options_contrato_dias_contrato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='usuario',
            new_name='fk_usuario',
        ),
    ]
