# Generated by Django 5.1.3 on 2025-02-10 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_rename_usuario_contrato_fk_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='dias_contrato',
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_contrato',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor del Contrato'),
        ),
        migrations.AddField(
            model_name='materia',
            name='fk_programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.programa', verbose_name='Programa al que Pertenece'),
        ),
        migrations.AddField(
            model_name='materia',
            name='fk_semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.semestre', verbose_name='Semestre al que Pertenece'),
        ),
        migrations.AddField(
            model_name='materia',
            name='horas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total de Horas'),
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pensum', models.IntegerField(blank=True, null=True, verbose_name='Pensum')),
                ('fecha_apertura', models.DateField(blank=True, null=True, verbose_name='Fecha de Apertura')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('vigente', models.BooleanField(default=False)),
                ('fk_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.programa', verbose_name='Programa al que Pertenece')),
            ],
            options={
                'verbose_name': 'Pensum',
                'verbose_name_plural': 'Pensums',
                'db_table': 'pensums',
            },
        ),
        migrations.AddField(
            model_name='materia',
            name='fk_pensum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.pensum', verbose_name='Pensum al que Pertenece'),
        ),
    ]
