# Generated by Django 5.1.3 on 2025-02-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_contrato_dias_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='total_dias_laborados',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Dias Laborados'),
        ),
        migrations.CreateModel(
            name='DetalleContratro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mes_a_pagar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mes a Pagar')),
                ('dias_laborados', models.IntegerField(blank=True, null=True, verbose_name='Dias Laborados')),
                ('valor_a_pagar', models.IntegerField(blank=True, null=True, verbose_name='Valor a Pagar')),
                ('fk_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contrato', verbose_name='Contrato')),
            ],
        ),
    ]
