# Generated by Django 5.1.3 on 2025-02-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_detallecontratro_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detallecontratro',
            table='detalles_contrato',
        ),
    ]
