# Generated by Django 5.1.3 on 2025-02-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_contrato_vigencia_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleacademico',
            name='codigo_convalidacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detalleacademico',
            name='codigo_pais',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleacademico',
            name='ies_codigo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detalleacademico',
            name='institucion_extranjera',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detalleacademico',
            name='metodologia_programa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
