# Generated by Django 5.1.3 on 2025-03-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_detalleexperiencialaboral_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleexperiencialaboral',
            name='trabajando_actualmente',
            field=models.BooleanField(default=False),
        ),
    ]
