# Generated by Django 5.1.3 on 2025-03-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_detalleexperiencialaboral_trabajando_actualmente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleexperiencialaboral',
            name='trabajando_actualmente',
        ),
    ]
