# Generated by Django 5.1.3 on 2025-04-28 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_detalleexperiencialaboral_trabajando_actualmente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargaacademica',
            old_name='aprobado',
            new_name='aprobado_contabilidad',
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='aprobado_rectoria',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='aprobado_vicerrectoria',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='fecha_aprobacion_contabilidad',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Aprobación Contabilidad'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='fecha_aprobacion_rectoria',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Aprobación Rectoría'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='fecha_aprobacion_vicerrectoria',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Aprobación Vicerrectoria'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='fk_aprobado_contabilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobacion_contabilidad', to=settings.AUTH_USER_MODEL, verbose_name='Aprobación Contabilidad'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='fk_aprobado_rectoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobacion_rectoria', to=settings.AUTH_USER_MODEL, verbose_name='Aprobación Rectoría'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='fk_aprobado_vicerrectoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobacion_vicerrectoria', to=settings.AUTH_USER_MODEL, verbose_name='Aprobación Vicerrectoria'),
        ),
    ]
