# Generated by Django 5.1.3 on 2025-04-28 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_rename_aprobado_cargaacademica_aprobado_contabilidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaCompartida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_carga_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cargaacademica', verbose_name='Carga Académica')),
                ('fk_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Materia Compartida',
                'verbose_name_plural': 'Materias Compartidas',
                'db_table': 'materias_compartidas',
            },
        ),
    ]
