# Generated by Django 5.1.3 on 2025-04-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_materiacompartida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargaacademica',
            name='aprobado_contabilidad',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='aprobado_rectoria',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='aprobado_vicerrectoria',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='materia_compartida',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Materia Compartida'),
        ),
    ]
