# Generated by Django 5.1.3 on 2025-04-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_alter_cargaacademica_aprobado_contabilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='auxilio_transporte',
            field=models.IntegerField(blank=True, null=True, verbose_name='Auxilio de Transporte'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='salario_minimo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Salario Mínimo'),
        ),
    ]
