# Generated by Django 5.1.3 on 2025-05-03 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_periodo_auxilio_transporte_periodo_salario_minimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaacademica',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carga_academica_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carga_academica_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por'),
        ),
    ]
