# Generated by Django 5.1.3 on 2025-05-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_cargaacademica_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaacademica',
            name='total_horas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Total Horas'),
        ),
    ]
