# Generated by Django 5.1.3 on 2025-05-08 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_cargaacademica_total_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiacompartida',
            name='fk_periodo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.periodo', verbose_name='Periodo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.programa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.semestre'),
        ),
        migrations.CreateModel(
            name='MateriaAprobada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_aprobacion', models.DateField()),
                ('estudiante', models.ForeignKey(limit_choices_to={'fk_rol__rol': 'E'}, on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.materia')),
            ],
            options={
                'verbose_name': 'Materia Aprobada',
                'verbose_name_plural': 'Materias Aprobadas',
                'unique_together': {('estudiante', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(limit_choices_to={'fk_rol__rol': 'E'}, on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.materia')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'unique_together': {('estudiante', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='Prerrequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_principal', to='home.materia')),
                ('prerequisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_requerida', to='home.materia')),
            ],
            options={
                'verbose_name': 'Prerrequisito',
                'verbose_name_plural': 'Prerrequisitos',
                'unique_together': {('materia', 'prerequisito')},
            },
        ),
    ]
