# Generated by Django 5.1.3 on 2025-05-08 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_cargaacademica_total_horas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ultimo_nivel_estudio',
        ),
        migrations.AddField(
            model_name='materiacompartida',
            name='fk_periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.periodo', verbose_name='Periodo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='fk_ultimo_nivel_estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.nivelacademico'),
        ),
    ]
