# Generated by Django 5.1.3 on 2025-05-08 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_materiacompartida_fk_periodo_usuario_programa_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='materiaaprobada',
            table='MateriaAprobada',
        ),
        migrations.AlterModelTable(
            name='matricula',
            table='Matricula',
        ),
        migrations.AlterModelTable(
            name='prerrequisito',
            table='Prerrequisito',
        ),
    ]
