# Generated by Django 5.1.3 on 2025-05-10 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_materiaaprobada_table_alter_matricula_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='creditos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Créditos'),
        ),
        migrations.CreateModel(
            name='HistorialAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Reprobado', 'Reprobado')], max_length=50)),
                ('estudiante', models.ForeignKey(limit_choices_to={'fk_rol__rol': 'E'}, on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.periodo')),
            ],
        ),
    ]
