# Generated by Django 5.1.3 on 2025-05-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_alter_programa_auth_user_alter_contrato_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocontrato',
            name='aplica_a_rol',
        ),
    ]
