# Generated by Django 5.1.3 on 2025-05-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_alter_materia_creditos_historialacademico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='creditos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de Créditos'),
        ),
    ]
