# Generated by Django 5.1.3 on 2025-05-14 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_remove_tipocontrato_aplica_a_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='dedicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dedicación'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tipocontrato', verbose_name='Tipo Contrato'),
        ),
    ]
