# Generated by Django 5.1.3 on 2025-05-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_alter_materia_creditos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_estudiante',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
