# Generated by Django 5.1.3 on 2025-05-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_usuario_codigo_estudiante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiaaprobada',
            options={'verbose_name': 'Materia Cursada', 'verbose_name_plural': 'Materias Cursadas'},
        ),
        migrations.RenameField(
            model_name='materiaaprobada',
            old_name='fecha_aprobacion',
            new_name='fecha_finalizacion',
        ),
        migrations.AddField(
            model_name='materiaaprobada',
            name='estado_aprobacion',
            field=models.CharField(choices=[('aprobada', 'Aprobada'), ('reprobada', 'Reprobada')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='materiaaprobada',
            table='materia_cursada',
        ),
    ]
