# Generated by Django 5.1.3 on 2025-05-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_contrato_dedicacion_alter_contrato_tipo_contrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='tipo_contrato',
            new_name='fk_tipo_contrato',
        ),
    ]
