# Generated by Django 5.1.3 on 2025-05-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_rename_tipo_contrato_contrato_fk_tipo_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensum',
            name='fecha_apertura',
        ),
        migrations.RemoveField(
            model_name='pensum',
            name='fecha_cierre',
        ),
    ]
