# Generated by Django 5.1.3 on 2025-05-11 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_alter_materiaaprobada_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('docente', models.ForeignKey(limit_choices_to={'fk_rol__rol': 'D'}, on_delete=django.db.models.deletion.CASCADE, to='home.usuario', verbose_name='Docente asignado')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.materia', verbose_name='Materia asignada')),
            ],
            options={
                'verbose_name': 'Materia-Docente',
                'verbose_name_plural': 'Materias-Docentes',
                'db_table': 'materias_docentes',
                'unique_together': {('docente', 'materia')},
            },
        ),
    ]
