# Generated by Django 5.1.3 on 2025-05-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_materiadocente'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_docente',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
