# Generated by Django 5.1.3 on 2025-05-15 20:52

import builtins
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_remove_pensum_fecha_apertura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Empleado',
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': [builtins.id], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleados',
        ),
    ]
