# Generated by Django 5.1.3 on 2025-05-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_usuario_codigo_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensum',
            name='fecha_apertura',
        ),
        migrations.RemoveField(
            model_name='pensum',
            name='fecha_cierre',
        ),
        migrations.RemoveField(
            model_name='pensum',
            name='pensum',
        ),
        migrations.AddField(
            model_name='pensum',
            name='codigo_pensum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Codigo Pensum'),
        ),
    ]
