# Generated by Django 5.1.3 on 2025-05-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_rename_usuario_empleado_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensum',
            name='pensum',
        ),
        migrations.AddField(
            model_name='pensum',
            name='codigo_pensums',
            field=models.IntegerField(blank=True, null=True, verbose_name='Codigo Pensum'),
        ),
    ]
