# Generated by Django 5.1.3 on 2025-05-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_remove_pensum_fecha_apertura_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materiaaprobada',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='materiaaprobada',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='materiaaprobada',
            name='materia',
        ),
        migrations.AlterUniqueTogether(
            name='materiadocente',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='materiadocente',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='materiadocente',
            name='materia',
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='materia',
        ),
        migrations.AlterUniqueTogether(
            name='prerrequisito',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='prerrequisito',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='prerrequisito',
            name='prerequisito',
        ),
        migrations.DeleteModel(
            name='HistorialAcademico',
        ),
        migrations.DeleteModel(
            name='MateriaAprobada',
        ),
        migrations.DeleteModel(
            name='MateriaDocente',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
        migrations.DeleteModel(
            name='Prerrequisito',
        ),
    ]
