# Generated by Django 5.1.3 on 2025-05-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_rename_codigo_pensums_pensum_codigo_pensum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
