# Generated by Django 5.1.3 on 2025-05-19 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_alter_empleado_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='arl',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='caja_compensacion',
        ),
        migrations.AddField(
            model_name='empleado',
            name='fk_afp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.afp'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fk_arl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.arl'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fk_caja_compensacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cajacompensacion'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fk_departamento_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.departamento'),
        ),
    ]
