# Generated by Django 5.1.3 on 2025-05-20 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_remove_empleado_arl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='afp',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='departamento_residencia',
        ),
        migrations.AddField(
            model_name='contrato',
            name='fk_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.periodo', verbose_name='Periodo de contratación'),
        ),
    ]
