# Generated by Django 5.1.3 on 2025-05-20 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_remove_empleado_afp_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nivelacademico',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='nivelacademico',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='nivelacademico',
            name='tarifa_base_por_hora',
        ),
        migrations.RemoveField(
            model_name='nivelacademico',
            name='vigencia',
        ),
        migrations.CreateModel(
            name='NivelAcademicoHistorico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarifa_base_por_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('año_vigencia', models.PositiveIntegerField()),
                ('fk_nivel_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.nivelacademico')),
            ],
            options={
                'verbose_name': 'Nivel Académico Histórico',
                'verbose_name_plural': 'Niveles Académicos Históricos',
                'db_table': 'niveles_academicos_historico',
                'unique_together': {('fk_nivel_academico', 'año_vigencia')},
            },
        ),
    ]
