# Generated by Django 5.1.3 on 2025-05-20 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_alter_nivelacademico_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fk_sede_donde_labora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sede'),
        ),
    ]
