# Generated by Django 5.1.3 on 2025-05-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_empleado_fk_sede_donde_labora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='sede_donde_labora',
        ),
    ]
