# Generated by Django 5.1.3 on 2025-05-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_remove_empleado_sede_donde_labora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='dedicacion',
        ),
    ]
