# Generated by Django 5.1.3 on 2025-05-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_remove_contrato_dedicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='dedicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dedicación'),
        ),
    ]
