# Generated by Django 5.1.3 on 2025-05-21 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_contrato_dedicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='auth_user',
        ),
        migrations.CreateModel(
            name='EmpleadoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fk_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='home.empleado', verbose_name='Empleado')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to=settings.AUTH_USER_MODEL, verbose_name='User Asignado')),
            ],
            options={
                'verbose_name': 'EmpleadoUser',
                'verbose_name_plural': 'EmpleadoUsers',
                'db_table': 'empleado_user',
                'unique_together': {('fk_empleado', 'fk_user')},
            },
        ),
    ]
