# Generated by Django 5.1.3 on 2025-05-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_remove_empleado_auth_user_empleadouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Año'),
        ),
    ]
