# Generated by Django 5.1.3 on 2025-05-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_alter_periodo_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='periodo',
            unique_together={('year', 'periodo')},
        ),
    ]
