# Generated by Django 5.1.3 on 2025-05-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_alter_periodo_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='horas',
        ),
        migrations.AddField(
            model_name='materia',
            name='horas_semanales',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas Semanales'),
        ),
    ]
