# Generated by Django 5.1.3 on 2025-05-22 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_remove_materia_horas_materia_horas_semanales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dedicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corto', models.CharField(max_length=10, verbose_name='Nombre Corto')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Corto')),
            ],
            options={
                'verbose_name': 'Dedicación',
                'verbose_name_plural': 'Dedicaciones',
                'db_table': 'dedicacion',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='fk_dedicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.dedicacion', verbose_name='Dedicación'),
        ),
    ]
