# Generated by Django 5.1.3 on 2025-05-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_dedicacion_contrato_fk_dedicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='eps',
            name='nombre_corto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
