# Generated by Django 5.1.3 on 2025-05-22 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_eps_nombre_corto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado de Revisión',
                'verbose_name_plural': 'Estados de Revisión',
                'db_table': 'estado_revision',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='fk_estado_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.estadorevision'),
        ),
    ]
