# Generated by Django 5.1.3 on 2025-05-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_estadorevision_empleado_fk_estado_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='estado_revision',
        ),
    ]
