# Generated by Django 5.1.3 on 2025-05-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_remove_empleado_estado_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='dedicacion',
        ),
    ]
