# Generated by Django 5.1.3 on 2025-05-23 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_remove_contrato_dedicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargaacademica',
            name='horas_semanales',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas Semanales'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='total_horas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Horas'),
        ),
        migrations.CreateModel(
            name='FuncionesSustantivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_administrativas', models.IntegerField(blank=True, null=True, verbose_name='Horas por Administrativas')),
                ('horas_docencia', models.IntegerField(blank=True, null=True, verbose_name='Horas por Docencia')),
                ('horas_investigacion', models.IntegerField(blank=True, null=True, verbose_name='Horas por Investigación')),
                ('horas_otras_actividades', models.IntegerField(blank=True, null=True, verbose_name='Horas por Otras Actividades')),
                ('horas_proyeccion_extension', models.IntegerField(blank=True, null=True, verbose_name='Horas por Proyección y Extensión')),
                ('fk_carga_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cargaacademica', verbose_name='Carga Académica')),
            ],
            options={
                'verbose_name': 'FuncionesSustantivas',
                'verbose_name_plural': 'FuncionesSustantivass',
                'db_table': 'funciones_sustantivas',
            },
        ),
    ]
