# Generated by Django 5.1.3 on 2025-05-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_alter_cargaacademica_horas_semanales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargaacademica',
            old_name='creado_por',
            new_name='fk_creado_por',
        ),
        migrations.RenameField(
            model_name='cargaacademica',
            old_name='modificado_por',
            new_name='fk_modificado_por',
        ),
    ]
