# Generated by Django 5.1.3 on 2025-05-23 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_rename_creado_por_cargaacademica_fk_creado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fk_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_user', to='home.programa', verbose_name='Programa')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_programa', to=settings.AUTH_USER_MODEL, verbose_name='User Asignado')),
            ],
            options={
                'verbose_name': 'ProgramaUser',
                'verbose_name_plural': 'ProgramaUsers',
                'db_table': 'programa_user',
                'unique_together': {('fk_programa', 'fk_user')},
            },
        ),
    ]
