# Generated by Django 5.1.3 on 2025-05-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_rename_valor_contrato_contrato_valor_mensual_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargaacademica',
            name='aprobado_contabilidad',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='aprobado_rectoria',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='aprobado_vicerrectoria',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
    ]
