# Generated by Django 5.1.3 on 2025-05-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_alter_cargaacademica_aprobado_contabilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargaacademica',
            name='fecha_aprobacion_contabilidad',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha Aprobación Contabilidad'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='fecha_aprobacion_rectoria',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha Aprobación Rectoría'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='fecha_aprobacion_vicerrectoria',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha Aprobación Vicerrectoria'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='horas_semanales',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Horas Semanales'),
        ),
        migrations.AlterField(
            model_name='cargaacademica',
            name='total_horas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Total Horas'),
        ),
    ]
