# Generated by Django 5.1.3 on 2025-06-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0085_alter_cargaacademica_fecha_aprobacion_contabilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecontratro',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
