# Generated by Django 5.1.3 on 2025-06-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_detallecontratro_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecontratro',
            name='activo',
        ),
        migrations.AddField(
            model_name='detallecontratro',
            name='vigente',
            field=models.BooleanField(default=False, verbose_name='Vigente'),
        ),
    ]
