# Generated by Django 5.1.3 on 2025-06-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0087_remove_detallecontratro_activo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuncionesSustantivas',
        ),
    ]
