# Generated by Django 5.1.3 on 2025-06-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_materiacompartida_fk_materia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarifa',
        ),
    ]
