# Generated by Django 5.1.3 on 2025-06-09 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0091_delete_tarifa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargaacademica',
            name='aprobado_contabilidad',
        ),
        migrations.RemoveField(
            model_name='cargaacademica',
            name='aprobado_rectoria',
        ),
        migrations.RemoveField(
            model_name='cargaacademica',
            name='fecha_aprobacion_contabilidad',
        ),
        migrations.RemoveField(
            model_name='cargaacademica',
            name='fecha_aprobacion_rectoria',
        ),
        migrations.RemoveField(
            model_name='cargaacademica',
            name='fk_aprobado_contabilidad',
        ),
        migrations.RemoveField(
            model_name='cargaacademica',
            name='fk_aprobado_rectoria',
        ),
        migrations.AddField(
            model_name='contrato',
            name='aprobado_contabilidad',
            field=models.BooleanField(default=False, verbose_name='Aprobado Contabilidad'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='aprobado_presidencia',
            field=models.BooleanField(default=False, verbose_name='Aprobado Presidencia'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='aprobado_rectoria',
            field=models.BooleanField(default=False, verbose_name='Aprobado Rectoría'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_aprobacion_contabilidad',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha Aprobación Contabilidad'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_aprobacion_presidencia',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha Aprobación Presidencia'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_aprobacion_rectoria',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha Aprobación Rectoría'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fk_aprobado_contabilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobacion_contabilidad', to=settings.AUTH_USER_MODEL, verbose_name='Aprobación Contabilidad'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fk_aprobado_presidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobacion_presidencia', to=settings.AUTH_USER_MODEL, verbose_name='Aprobación Presidencia'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fk_aprobado_rectoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobacion_rectoria', to=settings.AUTH_USER_MODEL, verbose_name='Aprobación Rectoría'),
        ),
    ]
