# Generated by Django 5.1.3 on 2025-06-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0092_remove_cargaacademica_aprobado_contabilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
