# Generated by Django 5.1.3 on 2025-06-11 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fk_pais_nacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.pais'),
        ),
    ]
