# Generated by Django 5.1.3 on 2025-06-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0095_empleado_fk_pais_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='codigo_pais',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pais',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre_pais',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
