# Generated by Django 5.1.3 on 2025-06-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0096_pais_codigo_pais_pais_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='nombre_corto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Corto'),
        ),
    ]
