# Generated by Django 5.1.3 on 2025-06-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0097_programa_nombre_corto'),
    ]

    operations = [
        migrations.AddField(
            model_name='dedicacion',
            name='horas_maximas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas Máximas'),
        ),
        migrations.AddField(
            model_name='dedicacion',
            name='horas_minimas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas Mínimas'),
        ),
    ]
